### ISSUE TITLE
Focus on Linux

### ISSUE THREAD

**Issue by iSpec** [iSpec/Hyperdrive#2]
Ryan, thanks for your help on Windows. However, I think that since Windows is already pretty good we should focus on Linux to make it equally as amazing. I will continue to maintain the Windows scripts, but I need you to focus on Linux for now.

**Comment by lighthouse64** [comment]
Sure.  I don't know if I'll be doing much right now though, since I'm on vacation.

**Comment by lighthouse64** [comment]
I've done a lot on Linux, and it has improved.
